# -*- coding: utf-8 -*-
"""ProyectoDS_Siniestralidad_Vial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4TeJlsoeOao-0qIiC4GkwwAOZBnayHa

**Contexto:**

*Este dataset contiene información sobre las muertes viales registradas en la República Argentina entre 2017 y 2024, recopilada a través del Sistema de Alerta Temprana (SAT), perteneciente al Sistema Nacional de Información Criminal (SNIC). Los datos corresponden a microdatos e informes sobre personas fallecidas como consecuencia de hechos de tránsito, permitiendo analizar la distribución y evolución de las muertes viales en el país.*

Dataset Elegido: SAT-MV-BU.xlsx

Fuente: https://datos.gob.ar/dataset/muertes-viales-sistema-de-alerta-temprana-estadisticas-criminales-en-la-republica-argentina

##**OBJETIVO PRINCIPAL**

Analizar las características temporales y contextuales de los hechos viales registrados en Argentina entre 2017 y 2024 y desarrollar un modelo de clasificación  que permita predecir la modalidad del hecho (modo_produccion_hecho_ampliada) distinguiendolos entre si:

TIPOS HECHOS:

* Colisión vehículo-vehículo,
* Vuelco/despiste,
* colisión vehículo-persona (atropello)
* colisión vehículo-objeto.

## **PREGUNTA DEL NEGOCIO**

# ***¿Qué tipo de siniestro podemos esperar según las condiciones observadas: clima, franja horaria y tipo de lugar, pudiendo analizar los resultados por provincia y a lo largo de los años 2017–2024?***

## **Variable objetivo:**

**tipo de siniestro** (modo_produccion_hecho_ampliada)

##**Variables predictoras:**
**clima** (clima_condicion)

**dónde se produce** (tipo_lugar)

**franja horaria** (hora_hecho)

##**Variables que usaremos para análisis/filtros:**

**ubicación geográfica** (provincia_nombre)

**a lo largo del tiempo** (anio)
"""

# 💻 Imports y configuración
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


print("pandas    ", pd.__version__)
print("numpy     ", np.__version__)
print("seaborn   ", sns.__version__)

"""ETAPA 1: OBTENCION DE LA INFORMACION GENERAL DEL DATASET"""

df = pd.read_csv("./SAT-MV-BU.csv")
print("TIPOS DE DATOS Y VALORES FALTANTES DE CADA COLUMNA")
df.info()
print("NUMERO TOTAL DE FILAS:",df.shape[0])
print("NUMERO TOTAL DE COLUMNAS",df.shape[1])

df

df.isna().sum()

"""ETAPA 2: EDA - SELECCION DE COLUMNAS Y LIMPIEZA DEL DATASET"""

#Seleccion de las columnas que utilizaremos para el análisis y predicción

columnas = [
    "modo_produccion_hecho_ampliada",
    "clima_condicion",
    "hora_hecho",
    "tipo_lugar",
    "provincia_nombre",
    "anio"
]

df_modelo = df[columnas].copy()

print("Nuestro Dataset para el proyecto")
df_modelo

faltantes = pd.DataFrame({                #Hacemos un breve revisión
    "cantidad": df_modelo.isna().sum(),
    "porcentaje": df_modelo.isna().mean() * 100
})

faltantes

#Revisamos la variable objetivo
df_modelo["modo_produccion_hecho_ampliada"].value_counts(dropna=False)

print(f"Hay {df_modelo["modo_produccion_hecho_ampliada"].nunique()} categorías diferentes de la variable que vamos a predecir.")   #¿qué categoría de siniestro es más probable?

#Revisamos las variables predictoras
df_modelo["hora_hecho"].describe()

for col in ["clima_condicion", "tipo_lugar", "provincia_nombre"]:   # Observamos diferencias de escritura;singular/plural; abreviaturas; categorías equivalentes; errores evidentes.
    print(f"\n--- {col} ---")
    print(df_modelo[col].value_counts(dropna=False).head(15))

# SECUENCIA
# normalizar → unificar categorías → transformar tipos → crear variables → revisar → preparar para ML.
# normalizamos escritura: mayúsculas/minúsculas; espacios sobrantes; acentos.

columnas_texto = [
    "modo_produccion_hecho_ampliada",
    "clima_condicion",
    "tipo_lugar",
    "provincia_nombre"
]

for col in columnas_texto:
    df_modelo[col] = (
        df_modelo[col]
        .astype("string")
        .str.strip()
        .str.lower()
    )

# Comprobamos la normalización

df_modelo["provincia_nombre"].unique()



#Transformar hora_hecho, los valores que no puedan convertirse pasan a NaN
df_modelo["hora_hecho"] = pd.to_datetime(
    df_modelo["hora_hecho"],
    format="%H:%M:%S",
    errors="coerce"
)

df_modelo["hora_hecho"] = df_modelo["hora_hecho"].dt.hour

def clasificar_franja(hora):
    if pd.isna(hora):
        return "desconocida"
    elif 6 <= hora < 12:
        return "mañana"
    elif 12 <= hora < 18:
        return "tarde"
    elif 18 <= hora < 24:
        return "noche"
    else:
        return "madrugada"

df_modelo["franja_horaria"] = df_modelo["hora_hecho"].apply(clasificar_franja)

df_modelo

df_modelo["franja_horaria"].unique()

df_modelo["franja_horaria"].value_counts()

"""# Para tener una idea más clara de la variable objetivo, hacemos algunas visualizaciones

"""

import seaborn as sns
import matplotlib.pyplot as plt

print("Nos permite saber si tenemos categorías muy dominantes. Esto será importante después porque una fuerte desproporción puede afectar al clasificador.")

orden = df_modelo["modo_produccion_hecho_ampliada"].value_counts().index

plt.figure(figsize=(10, 5))
sns.countplot(
    data=df_modelo,
    y="modo_produccion_hecho_ampliada",
    order=orden
)
plt.title("¿Qué tipos de siniestro predominan?")
plt.xlabel("Cantidad")
plt.ylabel("Tipo de siniestro")
plt.show()
tabla_franja = pd.crosstab(
    df_modelo["franja_horaria"],
    df_modelo["modo_produccion_hecho_ampliada"]
)

tabla_franja.plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Tipos de siniestro según franja horaria")
plt.xlabel("Franja horaria")
plt.ylabel("Cantidad")
plt.xticks(rotation=0)
plt.legend(title="Tipo de siniestro")
plt.show()

tabla_clima = pd.crosstab(
    df_modelo["clima_condicion"],
    df_modelo["modo_produccion_hecho_ampliada"]
)

tabla_clima.plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Tipos de siniestro según condición climática")
plt.xlabel("Clima")
plt.ylabel("Cantidad")
plt.xticks(rotation=45, ha="right")
plt.legend(title="Tipo de siniestro")
plt.tight_layout()
plt.show()

evolucion = (
    df_modelo
    .groupby(["anio", "modo_produccion_hecho_ampliada"])
    .size()
    .reset_index(name="cantidad")
)

plt.figure(figsize=(12, 6))
sns.lineplot(
    data=evolucion,
    x="anio",
    y="cantidad",
    hue="modo_produccion_hecho_ampliada",
    marker="o"
)

plt.title("Evolución de los tipos de siniestro, 2017–2024")
plt.xlabel("Año")
plt.ylabel("Cantidad")
plt.show()

df_modelo["provincia_nombre"].value_counts().head(10).plot(
    kind="bar",
    figsize=(10, 5)
)

plt.title("Cantidad de registros por provincia")
plt.xlabel("Provincia")
plt.ylabel("Cantidad")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

df_modelo["modo_produccion_hecho_ampliada"] = (
    df["modo_produccion_hecho_ampliada"]
    .astype("string")
    .str.strip()
    .str.lower()
)

"""Al graficar observamos que tiene sentido reducir las 16 categorías a 5 grupos, porque estamos buscando un modelo que pueda generalizar y no aprender categorías muy poco frecuentes. La agrupación además tiene una lógica de interpretación del tipo de siniestro.

* Grupo 1: colisiones entre vehículos.
* Grupo 2: vehículo contra persona.
* Grupo 3: pérdida de control del vehículo.
* Grupo 4: colisiones con otros elementos.
* Grupo 5: resto de modalidades.
"""

df_modelo["modo_produccion_hecho_ampliada"].value_counts()

df_modelo["modo_produccion_hecho_ampliada"] = (
    df["modo_produccion_hecho_ampliada"]
    .astype("string")
    .str.strip()
    .str.lower()
)

grupo_siniestro = {
    "colisión vehículo-vehículo": "1",
    "colisión múltiple": "1",

    "colisión vehículo-persona": "2",

    "vuelco-despistes": "3",
    "derrape": "3",

    "colisión vehículo-animal": "4",
    "colisión vehículo-objeto": "4",
    "colisión vehículo-tracción a sangre": "4",
    "colisión vehículo-vehículo estacionado": "4"
}

df_modelo["modo_produccion_hecho_ampliada"] = (
    df_modelo["modo_produccion_hecho_ampliada"]
    .map(grupo_siniestro)
    .fillna("5")
)

df_modelo["modo_produccion_hecho_ampliada"].value_counts().sort_index()

"""# **Aprendizaje Supervisado**
*¿Qué tipo de siniestro podemos esperar según clima, hora/franja horaria, lugar y provincia?*
"""

# Variable objetivo (y)
y = df_modelo["modo_produccion_hecho_ampliada"]

# Variables predictoras (X)
X = df_modelo[
    ["clima_condicion", "franja_horaria", "tipo_lugar", "provincia_nombre"]
]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Todas nuestras variables predictoras son categóricas. Vamos a utilizar One-Hot Encoding. Para ello usamos un Pipeline y ColumnTransformer.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columnas_categoricas = [
    "clima_condicion",
    "franja_horaria",
    "tipo_lugar",
    "provincia_nombre"
]

preprocesador = ColumnTransformer(
    transformers=[
        (
            "categoricas",
            OneHotEncoder(handle_unknown="ignore"),   #Puede ocurrir que una categoría aparezca en X_test pero no haya aparecido durante el entrenamiento. En vez de generar un error, el codificador simplemente la ignora.
            columnas_categoricas
        )
    ]
)

"""**Primer modelo: Regresión Logística**"""

# Creamos el pipeline:

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

modelo = Pipeline([
    ("preprocesamiento", preprocesador),
    ("clasificador", LogisticRegression(
        max_iter=1000
    ))
])

# Y entrenamos
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

y_pred[:20]